### ISSUE TITLE
No support for Windows Authentication on Nuget feeds?

### ISSUE THREAD

**Issue by celer1tas** [OneGet/NuGetProvider#1]
When do we get support for installing powershell modules from private nuget feeds configured with Windows Authentication (or any other authentication)?

Currently all PowershellGet *-Module functions (Get-Module,Find-Module, Install-Module, Publish-Module,etc) only connect to public nuget feeds. The same applies to Microsoft.PackageManagement.NuGetProvider.dll

Thanks

**Comment by jianyunt** [comment]
[WMF 5.1 preview](https://www.microsoft.com/en-us/download/details.aspx?id=53347) should contain the fix.
