### ISSUE TITLE
unable to install package Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by MartinHBA** [OneGet/NuGetProvider#62]
Hello, I am unable to install nuget package with
```PowerShell
 Install-Package  Microsoft.Data.SqlClient -Provider nuget -Force
```
It will result in error below:
```PowerShell
PS C:\WINDOWS\system32> Install-Package Microsoft.Data.SqlClient -Provider nuget -Force
Install-Package : Dependency loop detected for package 'Microsoft.Data.SqlClient'.
At line:1 char:1
+ Install-Package Microsoft.Data.SqlClient -Provider nuget -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : Deadlock detected: (Microsoft.Data.SqlClient:String) [Install-Package], Exception
    + FullyQualifiedErrorId : DependencyLoopDetected,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```
only way to install this package is with skipdependencies parameter:
```PowerShell
Install-Package Microsoft.Data.SqlClient -Provider nuget -skipdependencies
```
I am pretty sure there is no loop in dependency, Package Manager in visual studio C# project is able to load this nuget package without any issue

**Comment by dafanasiev** [comment]
I think that this is bug. See: https://github.com/dotnet/runtime/issues/31065

**Comment by rbleattler** [comment]
Has there been any movement here? This is still an issue.

**Comment by MartinHBA** [comment]
@rbleattler it's resolved by evolution. 
STEP 1: install Powershell 7
STEP 2: run Powershell 7 as administrator
STEP 3: Install-Package  Microsoft.Data.SqlClient
DONE

**Comment by potatoqualitee** [comment]
Thanks for that solution, @MartinHBA !

**Comment by ps-vishnu** [comment]
@MartinHBA I have followed the steps but nothing is showing up after Install-Package Microsoft.Data.SqlClient
![image](https://user-images.githubusercontent.com/24964290/128023910-a5efab94-6a90-4997-b529-ec1d624878dc.png)

**Comment by Verayth** [comment]
PS C:\windows\system32> pwsh
PowerShell 7.1.4
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Windows\System32> Install-Package Microsoft.Data.SqlClient
Install-Package: Dependency loop detected for package 'Microsoft.Data.SqlClient'.
PS C:\Windows\System32>

**Comment by potatoqualitee** [comment]
@Verayth -- the command you're looking for is `Install-Package Microsoft.Data.SqlClient -SkipDependencies`

**Comment by elthombre** [comment]
@potatoqualitee , @Verayth , aren't there risks when using -SkipDependencies

**Comment by potatoqualitee** [comment]
@elthombre i just have to go get them myself. but yes, it can leave out dependencies of depedencies. now i just use a build with a csproj to make it all work :/
