### ISSUE TITLE
DefaultConfig for nuget config file produces invalid config

### ISSUE THREAD

**Issue by timheuer** [OneGet/NuGetProvider#65]
https://github.com/OneGet/NuGetProvider/blob/16519ed5cbbae967a1aeaa383614bcb4505f46ab/NugetLightRequest.cs#L85-L89

Is the default config for a nuget.config if not found in this provider code.  It produces an invalid nuget.config (no sources) and can result in a machine not being able to do any restores for apps or other things relying on nuget going forward.

**Comment by zivkan** [comment]
FWIW, this appears to be affecting a bunch of Azure Pipelines and GitHub Actions customers: https://github.com/actions/virtual-environments/issues/5768
